### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "role": "EventManager"
}
### Get User by ID
GET http://localhost:8080/api/users/1

### Update User
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "role": "CEO"
}

### Delete User
DELETE http://localhost:8080/api/users/1